# Format:
# version|JAVA_HOME|MAVEN_HOME

8|C:\Program Files\Java\jdk1.8.0_202|C:\Program Files\Maven\apache-maven-3.6.3
17|C:\Program Files\Java\jdk-17|C:\Program Files\Maven\apache-maven-3.9.11
21|C:\Program Files\Java\jdk-21|C:\Program Files\Maven\apache-maven-3.9.11